# Workflow Name
name: "generate_embeddings"

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches:
      - main

# Define the jobs to be run
jobs:
  generate:
    # Specify the virtual environment (Ubuntu latest version) for the job
    runs-on: ubuntu-latest

    # List the steps to execute in this job
    steps:
      # Step 1: Set up Node.js version 20
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Step 2: Checkout the repository code to access its files in this workflow
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 3: Generate embeddings for Markdown (or MDX) documentation files
      - name: Generate embeddings
        uses: PieterDePauw/embeddings-generator-vercel-postgres@v1.0.1
        with:
          # Vercel Postgres URL (via GitHub Secrets)
          database-url: ${{ secrets.POSTGRES_URL }}
          # OpenAI API Key (via GitHub Secrets)
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          # Root directory of the documentation files.
          # docs-root-path:
